sudo: True

language: python
python:
        - "2.7.8"
        - "2.7.9"
        - "2.7.10"
        - "3.2"
        - "3.3"
        - "3.4"
        - "3.5"
        - "pypy"

install:
        - "ls -l /usr/bin | grep python"
        - "pip install future cx_Freeze"

script:
        - "python -m pytest --verbose" 

notifications:
        - email: false

